# Generated by Django 6.0.5 on 2026-05-28 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paiement',
            name='moyen_paiement',
            field=models.CharField(blank=True, choices=[('orange', 'Orange Money'), ('airtel', 'Airtel Money'), ('mpesa', 'M-Pesa')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='date_paiement',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='numero_transaction',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echec', 'Échec')], default='paye', max_length=20),
        ),
        migrations.CreateModel(
            name='FraisScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_frais', models.CharField(choices=[('minerval', 'Minerval'), ('autre', 'Autre')], default='minerval', max_length=20)),
                ('mois', models.CharField(choices=[('septembre', 'Septembre'), ('octobre', 'Octobre'), ('novembre', 'Novembre'), ('decembre', 'Décembre'), ('janvier', 'Janvier'), ('fevrier', 'Février'), ('mars', 'Mars'), ('avril', 'Avril'), ('mai', 'Mai'), ('juin', 'Juin')], max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'frais scolaire',
                'verbose_name_plural': 'frais scolaires',
                'unique_together': {('type_frais', 'mois')},
            },
        ),
        migrations.AddField(
            model_name='paiement',
            name='frais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='payments.fraisscolaire'),
        ),
        migrations.AlterUniqueTogether(
            name='paiement',
            unique_together={('eleve', 'frais')},
        ),
    ]
