# Generated by Django 6.0.5 on 2026-05-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='valeur',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
