# Generated by Django 6.0.5 on 2026-05-28 20:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_notes_to_evaluationcours(apps, schema_editor):
    EvaluationCours = apps.get_model('dashboard', 'EvaluationCours')
    Note = apps.get_model('dashboard', 'Note')

    for note in Note.objects.all():
        evaluation_cours, created = EvaluationCours.objects.get_or_create(
            cours_id=note.cours_id,
            evaluation_id=note.evaluation_id,
            defaults={'note_max': 20, 'ponderation': 100},
        )
        note.evaluation_cours_id = evaluation_cours.pk
        note.save(update_fields=['evaluation_cours'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('dashboard', '0002_alter_note_valeur'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_max', models.DecimalField(decimal_places=0, default=20, max_digits=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('ponderation', models.DecimalField(decimal_places=2, default=100, help_text='Pondération en pourcentage (ex: 30 pour 30%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_config', to='dashboard.cours')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_config', to='dashboard.evaluation')),
            ],
            options={
                'verbose_name': 'configuration évaluation-cours',
                'verbose_name_plural': 'configurations évaluation-cours',
                'unique_together': {('cours', 'evaluation')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='note',
            name='evaluation_cours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='dashboard.evaluationcours'),
        ),
        migrations.RunPython(
            code=migrate_notes_to_evaluationcours,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='note',
            name='evaluation_cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='dashboard.evaluationcours'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('eleve', 'evaluation_cours')},
        ),
        migrations.RemoveField(
            model_name='note',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='note',
            name='evaluation',
        ),
    ]
