# Generated by Django 6.0.6 on 2026-06-08 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_professeur'),
        ('dashboard', '0004_evaluation_periode_alter_evaluation_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='accounts.classe'),
        ),
        migrations.AddField(
            model_name='cours',
            name='professeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='accounts.professeur'),
        ),
    ]
