# Generated by Django 6.0.6 on 2026-06-05 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Directeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('postnom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('titre', models.CharField(choices=[('directeur_general', 'Directeur Général'), ('directeur_adjoint', 'Directeur Adjoint'), ('censeur', 'Censeur'), ('prefet', 'Préfet des études'), ('autre', 'Autre')], default='directeur_general', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='directeur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'directeur',
                'verbose_name_plural': 'directeurs',
            },
        ),
    ]
